### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by trulore** [danghvu/mod_dumpost#14]
I think I see a bug in line 65:

65: state->buffer[state->log_size] = 0;

If we've filled the buffer completely, then state->log_size will equal LOG_IS_FULL, which is -1.  So you are assigning a 0 to buffer[-1] which can cause some interesting behavior in rare cases.  :)

**Comment by danghvu** [comment]
Hm I can't remember when `logit` function is called. If it is called outside of `dumpit` then you are right. We should fix it anyway :) good catch.

Do you have a test and possible patch ?

**Comment by trulore** [comment]
I'm afraid I don't have a test, because it rarely causes an issue, unless I put it in an infinite loop submitting huge requests.

As for a patch, I was thinking about something like this: 
[patch.txt](https://github.com/danghvu/mod_dumpost/files/404147/patch.txt)

**Comment by danghvu** [comment]
Looks good, could you PR ?

**Comment by trulore** [comment]
Sure!  I've created a branch called "issue_14_fix", and I've tested it pretty well.  Can you give me permissions to submit to this project?  I tried just now and I got "Permission to danghvu/mod_dumpost.git denied to trulore"

**Comment by danghvu** [comment]
Thansk, but you need to submit a [pull request](https://help.github.com/articles/using-pull-requests/)

**Comment by trulore** [comment]
Oh, no problem!  I definitely want to learn how to use GitHub.  We use a different Git tool.  But generally with any Git tool, you have to have a branch before you create a Pull request.   And when I click "New Pull Request" on your project, it's asking me which branches to merge, but I don't have a branch, and I don't see how to create one.  Maybe I'm missing privs?  When I try to push a branch from my local repository, I get "permission denied"

**Comment by trulore** [comment]
Okay, I created a fork, and then a pull request from the fork.  Apologies, we use a different git tool where I work, and the pull request process is different.   I'm learning!  :)

**Comment by danghvu** [comment]
We all have to learn it at some point, no worry :)
