### ISSUE TITLE
Customizable log format

### ISSUE THREAD

**Issue by brommer** [danghvu/mod_dumpost#16]
Hi,

it would be great to have a customizable log format. E.g. I have a use case, where I need response times and users sending the request. 

Thanks!

**Comment by danghvu** [comment]
For response time, can you do it with http://httpd.apache.org/docs/current/mod/mod_log_config.html ?

How do you obtain the user ? If it is in the header then user can specify the header field (or you can send it with the header/post)

**Comment by brommer** [comment]
Hi, but the "LogFormat" "CustomLog" directives are only reflected in the access.log and not in the dumpost specific logs, or am I wrong? I am parsing the dumpost logs with Elasticsearch, so it would be nice to have this information together in one line, without matching other log entries.

I guess the user information is in the authorization header. However, the authorization header contains the base64 string or the username:password, but I would like to log the username only (like in the normal log format with "%u". 

Thanks!

**Comment by danghvu** [comment]
So you want a combination with some access log features, It is probably out of the scope. But you can probably play in the source to your need using `request_rec->request_time ` and `request_rec->user`

**Comment by brommer** [comment]
Ok, thanks for the hint!
